### ISSUE TITLE
Square Reader

### ISSUE THREAD

**Issue by rolfdalhaug** [square/in-app-payments-react-native-plugin#2]
Hi

Quick query, does this plugin work with the with Square Reader to accept chip & PIN and contactless payments?..

**Comment by hukid** [comment]
@rolfdalhaug I guess you are looking for Square Reader SDK plugin: https://github.com/square/react-native-square-reader-sdk

**Comment by rolfdalhaug** [comment]
Thanks @hukid, I had seen that but it's currently US only. I guess we'll have to wait until it's fully released.

**Comment by StephenJosey** [comment]
@rolfdalhaug we definitely hear you, we can't wait until ReaderSDK is released in other countries as well. Definitely be on the lookout, but unfortunately we do not have an ETA at this time.

We do also have a Point of Sale API which does work in other countries, but unfortunately we do not have a React Native plugin for. It's similar to ReaderSDK, except that it requires the actual POS application to be installed on the device (and actually opens the POS app rather than integrated into your app). Check it out here if you're interested: https://docs.connect.squareup.com/payments/pos/overview
