### ISSUE TITLE
Android > Build Fails > Could not find com.squareup.sdk.in-app-payments:card-entry:1.3.0.

### ISSUE THREAD

**Issue by janva255** [square/in-app-payments-react-native-plugin#42]
### Describe the issue
When trying to build on android with `react-native run-android` I got this error 

```
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.squareup.sdk.in-app-payments:card-entry:1.3.0.
     Searched in the following locations:
       - file:/root/.m2/repository/com/squareup/sdk/in-app-payments/card-entry/1.3.0/card-entry-1.3.0.pom
[....]
```

It happened with version 1.2 first, then I updated to see if it fixed the issue but it didn't, I also got an error building ios with version 1.3.0, a problem with SquareBuyerVerificationSDK.

I tried to do react-native link but it didn't work also.

### To Reproduce
Run `react-native run-android`

### Expected behavior
Be able to run it and make the build

**Environment (please complete the following information):**
  - platform: Android
  - OS and version: Android 9
  - dev environment: MacOS
  - In-App Payments Plugin version: 1.3.0 (Also happened with 1.2.0)

  In addition: Run `react-native info` in your terminal and copy the results here.

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 741.50 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.16.0 - /usr/local/bin/node
    npm: 6.13.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.61.2
```

**Comment by okenshields** [comment]
Hi Joaquin,

Thanks for reporting the issue. The error you reported could be caused by different reasons. We suggest trying the following:
- Delete node_modules and re-install dependencies.
- Try clean and rebuild.
- Try build and run in Android Studio and see if it works there. (instead of using `react-native run-android`)

Please let us know if any of the above helps.
Also, can you please provide more info on the error you hit building iOS as well? Thanks!

**Comment by janva255** [comment]
@okenshields Looks like it works by building with android studio, but doesn't work with react-native run-android

**Comment by janva255** [comment]
@okenshields Is there anything I can do to make react-native run-android work?

**Comment by okenshields** [comment]
@janva255  To clarify, did you experience the issue with the example app or your own app?

**Comment by janva255** [comment]
@okenshields It's on my own app

**Comment by okenshields** [comment]
Happy New Year Joaquin!
Were you able to figure it out? It could be related to the way your environment is configured or the way your app is configured. Did you try running the example app we provide? If `run-android` works for the example app, then it's highly likely something not quite right with your app config. Otherwise, it's more likely caused by your environment.

**Comment by janva255** [comment]
@okenshields I could fix it, it was related to these properties in gradle.properties
org.gradle.daemon=
org.gradle.configureondemand=
org.gradle.jvmargs=
I just commented them and it worked
