### ISSUE TITLE
Implementation of the payment flow

### ISSUE THREAD

**Issue by rahamin1** [square/in-app-payments-react-native-plugin#54]
I would like to implement the card payment flow in my application, using my sandbox test account.

Can I implement the entire flow? In your quickstart app you do not complete the charge (using `chargeCardNonce` or a similar command), but print a curl command. Is this because it is impossible to complete the charging flow with a sandbox test account? If is is possible, then which method am I supposed to use for generating a nounce and for charging?

### An additional note
The links to `Apple Pay Usage` and `Google Pay Usage` in https://github.com/square/in-app-payments-react-native-plugin/blob/master/docs/get-started.md#process-overview are broken.

**Comment by StephenJosey** [comment]
Hey @rahamin1 you can definitely charge a sandbox nonce. By default, we print out the cURL command because it's easier. In order to have a full-flow, you need a backend server (which is the final step of the quickstart): https://github.com/square/in-app-payments-react-native-plugin/blob/master/react-native-in-app-payments-quickstart/README.md#step-6-optional---use-the-nonce-with-the-backend-server

Take a look there. It will guide you through two options: setting up a localhost server, or setting up a Heroku server (which we also have a quickstart Heroku server you can just use as well). Let me know if you run into any problems with this, though.

**Comment by rahamin1** [comment]
Oops, embarrassing... All is written there... Thank you!
