### ISSUE TITLE
Is there a method that gets card details and returns a nonce?

### ISSUE THREAD

**Issue by rahamin1** [square/in-app-payments-react-native-plugin#55]
I don't see such a method in the API reference, and the documentation describes a flow in which the card entry and nonce request are handled by `SQIPCardEntry.startCardEntryFlow`.

Is there a way that will enable me implement the card entry form and request the nonce when I have the card details? I prefer this way since it will make it easier for me to better tailor the UI to my needs (I know that I can customize your UI, but this is not sufficient for my app's design).

**Comment by StephenJosey** [comment]
No, there's no way to generate a card nonce without using the built-in form (`startCardEntryFlow`). You can use the nonce to save the card on file, and just charge the card directly without having the customer fill in their info though (since you mentioned that you have the card details). https://developer.squareup.com/docs/customers-api/cookbook/save-cards-on-file

**Comment by rahamin1** [comment]
Thanks Stephen. 
The page you referred to talks about JAVA Api. I assume, then, that I cannot do this in RN, right?

**Comment by StephenJosey** [comment]
I'm not sure I'm following your first question. What do you mean by "in which I have the credit card details with which I request a nonce..."? Are you saying if you already have credit card details stored somewhere? If so, we strongly recommend against that because that would require you to be PCI-compliant, instead of leaving it in Square's hands. If not, then can you clarify what you mean?

The saving card on file is a backend function, not part of the In App Payment. In fact, everything after you receive the nonce is something you need to do on a backend (PHP, Node, Java, etc). You need a server that is running a backend. You can pass the nonce to it and either charge it, or save a card to a customer.

Furthermore, you say "What I would like is to request the nonce based on the card details that I provide without saving it." -- that is exactly what the In-App Payments SDK does. It generates a form for a customer to enter their card information, and once submitted, it will generate a nonce in which your app can do something with (create a payment, or save the card on file). The entire purpose of the In-App Payments is to allow a customer to enter their CC details and generate a nonce.

To reiterate: we do not allow clients to send us raw credit card details. This would come with several security flaws that would need to be addressed, and is something we do not support at this time.

Please let me know if I'm misunderstanding, though.

**Comment by rahamin1** [comment]
Hey Stephen.

In "I have the credit card details" I mean that I have a form in my app that gets the credit card details, and when the user has entered these details I am not storing them anywhere, I just want to request a nonce using square's in-app-payments-react-native-plugin.

> Furthermore, you say "What I would like is to request the nonce based on the card details that I provide without saving it." -- that is exactly what the In-App Payments SDK does. It generates a form for a customer to enter their card information, and once submitted, it will generate a nonce in which your app can do something with 

What I am asking, as I wrote above, is to leave the form to me, and to have a square function that gets the card details from me and generate the nonce. Then I will ask the backend to create a payment.

**Comment by StephenJosey** [comment]
Right, as I mentioned in my original comment, you can't use a custom form to gather this information and pass it to us. You must use our form (which is the In-App Payments SDK), to collect the CC information at this time. We don't allow this in mobile or web due to security reasons, but I don't have the full details into the "why".

**Comment by rahamin1** [comment]
Thanks. If you can check what the reason is, it will be great.

**Comment by StephenJosey** [comment]
I mean, ultimately, it's so that Square will hold the burden of PCI compliance, so you don't have to. Even if you have your own form, you will still need to make sure you are PC-compliant, which can be a challenge for many folks. You can take a look here for info on Square's PCI-stance: https://squareup.com/guides/pci-compliance

**Comment by rahamin1** [comment]
Thanks. I hope that you still have patience for my nagging, but this is a bit vague...

The whole process: getting card details and generating the nonce is done on the handset, right? Are there any special measures that you take in order to make it secure/PCI-compliance? Are you encrypting the card details on the handset, or just taking them as is and generating the nonce?

If the later is true, then it seems that I can do the first part (getting card details) myself without risking PCI-compliance.

**Comment by StephenJosey** [comment]
I don't mind at all...unfortunately, after speaking with our payments team, we can't dive into too many of the details. Basically, and I know this is similar to my previous comment, Square provides our customers with a managed payments platform. A meaningful aspect of our offering is keeping our customers completely out of needing to worry about PCI compliance. As soon as any part of your code touches credit card details, you are now in scope for PCI compliance. Our platform is built to keep you out of that scope, hence the fact that we don’t offer a way for you to handle the credit card details.
