### ISSUE TITLE
Library not found

### ISSUE THREAD

**Issue by x956606865** [square/in-app-payments-react-native-plugin#81]
### Describe the issue

I just installed this step by step by the guild. But it cannot start and get the error "CodeSign failed" 

### To Reproduce

1. create a new project by "npx react-native init testRNP"

2.import the framework by this guild: https://developer.squareup.com/docs/in-app-payments-sdk/installation#option-3-install-the-in-app-payments-sdk-manually

I just follow the "Option 3: Install In-App Payments SDK manually" to import the SDK

3. install "in-app-payments-react-native-plugin" with yarn

4. init "in-app-payments-react-native-plugin" with this guild : https://github.com/square/in-app-payments-react-native-plugin/blob/master/docs/get-started.md

   And I still follow the "Step 3a: Add the In-App Payments SDK to your iOS project without CocoaPods
" to init the package

   by the way, I have set the build system to "Legacy Build System" 

5. start the app with "release" schema

### Expected behavior

expect start app successfully

**Environment (please complete the following information):**

### Screenshots

![image](https://user-images.githubusercontent.com/10432052/88907639-7006c380-d28b-11ea-960d-781577b901b2.png)

### Additional context

Because I created a new project and just installed only the package, So I'm sure the error is caused by this package.

Please help me...

**Comment by StephenJosey** [comment]
Thanks for reporting! Do you need "Legacy Build System"? I saw online that this can be caused be using legacy instead of the new build system. If that doesn't change anything, are you able to run the test example successfully (https://github.com/square/in-app-payments-react-native-plugin/tree/master/react-native-in-app-payments-quickstart)?

If so, can you provide your project somewhere so we can test it ourselves?
