### ISSUE TITLE
Card entry flow does not work within modal (iOS)

### ISSUE THREAD

**Issue by darajava** [square/in-app-payments-react-native-plugin#92]
### Describe the issue

When I try to open the Card Entry flow from within a modal, I recieve the following error (iOS only, Android works fine):

```
Warning: Attempt to present <UINavigationController: 0x7fba6b163400>  on <RNNSideMenuController: 0x7fba6b15fa00> which is already presenting <RCTModalHostViewController: 0x7fba6d798340>
```

### To Reproduce
Create a modal in React Native, place the card entry flow within.

### Expected behavior

The Card Entry flow starts from within a modal.

**Environment (please complete the following information):**

  - platform: [iOS]
  - OS and version: [iOS11]
  - dev environment: [MacOS]
  - In-App Payments Plugin version: [1.4.0]

**Comment by StephenJosey** [comment]
This is a limitation to iOS in general (that's a warning from iOS, not Square). Basically, you can't present another ViewController from the same place you're already presenting a ViewController. It sounds like you're attempting to present on the ViewController that is already presenting the modal, rather than the modal itself, or something to that nature.

**Comment by dutradotdev** [comment]
@darajava use a setTimeout to close your window and navigate to cardModal on iOS

**Comment by dutradotdev** [comment]
```js 
  const addNewCardHandler = async () => {
    onCloseModal();
    setTimeout(async () => {
      try {
        await showCardEntry(addCardToStore);
      } catch (e: unknown) {
        console.error('addNewCardHandler', JSON.stringify(e));
      }
    }, 500);
  };

```
